### ISSUE TITLE
Maintenance: integrate utility with CI/CD unit test processes 

### ISSUE THREAD

**Issue by ijemmy** [aws-powertools/powertools-lambda-typescript#1100]
## Description of the feature request

**Problem statement**
Even if the new utility won't be released till much later, whenever code is merged into `main` the code coverage should stay at 100%.

**Summary of the feature**
This unit of work tracks the activities and changes needed for the idempotency utility to be part of the unit test workflows that run whenever a PR is created and/or updated.

Additionally, the new utility should also be part of the `husky` hooks that are ran locally before committing.

**Code examples**
N/A

**Benefits for you and the wider AWS community**
N/A

**Describe alternatives you've considered**
None, tests must be there.

**Additional context**
N/A

### Related issues, RFCs

#447

**Comment by dreamorosi** [comment]
Hi @ijemmy I'm so sorry, I just noticed that there was this issue opened and I started working on this on Friday.

The reason why I worked on it so soon was that after merging #1110 the "on-merge" Action is failing due to inconsistencies in the `package-lock.json` file.

I would still appreciate your review on #1160 whenever you're ready next week.

Again, apologies for the confusion. Had I noticed that you already assigned this to you I would not have opened the PR and talked to you first.
