### ISSUE TITLE
Docs: mark the utility as public in the `package.json` file

### ISSUE THREAD

**Issue by ijemmy** [aws-powertools/powertools-lambda-typescript#1102]
## Description of the improvement

**Summary of the proposal**
As a part of the implementation of the utility it's necessary to have a dedicated readme file for the utility as well as update the main one in the root of the project.

The first one will be also used in the npm page, the latter will need to be updated to mention the new utility.

**How, where did you look for information**
Readme of both root and package.

**Missing or unclear documentation**
Info about the utility.

**Improvement**
N/A

### Related existing documentation

N/A

### Related issues, RFCs

#447

**Comment by dreamorosi** [comment]
In #1485 we already added the new `README.md` file for the Idempotency utility and we also have linked the new utility in the main readme file, so I'm repurposing this issue to mark the last tasks to be done before publishing, which are:

1. Update the `package.json` file of the utility

We need to remove the `private: "true"` field and add this one:
```json
"publishConfig": {
  "access": "public"
},
```

2. Make visible the documentation page

We need to add the utility to the `mkdocs.yml` file so that the page shows in the navbar of the docs
