### ISSUE TITLE
Bug: logging fails if input contains bigint values

### ISSUE THREAD

**Issue by samuelsulo** [aws-powertools/powertools-lambda-typescript#1117]
## Bug (logger): logging fails if input contains bigint values
Since ```JSON.stringify``` is unable to serialize bigint values, the logging function raises an exception if the input contains a bigint value.

### Expected Behavior
The logger should handle bigints to prevent ```JSON.stringify``` from raising an exception.

Log Request:
```typescript
import { Logger } from "@aws-lambda-powertools/logger";

const logger = new Logger();
logger.info('Object with bigint value', { myBigInt: BigInt(1234) })
```
Log Result:
```json
{
  "level": "INFO",
  "message": "Object with bigint value",
  "service": "service_undefined",
  "timestamp": "2022-10-12T22:27:17.067Z",
  "myBigInt": "1234"
}
```

### Current Behavior
The logger does not handle bigint values which causes ```JSON.stringify``` to raise an exception.

Log Request:
```typescript
import { Logger } from "@aws-lambda-powertools/logger";

const logger = new Logger();
logger.info('Object with bigint value', { myBigInt: BigInt(1234) })
```
Raised exception:
```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    ...
```

### Possible Solution

Handling bigint values in the ```removeCircularDependencies``` method of the ```Logger``` class should fix the issue.

Before
```typescript
private removeCircularDependencies(): (key: string, value: LogAttributes | Error) => void {
    const references = new WeakSet();

    return (key, value) => {
      let item = value;
      if (item instanceof Error) {
        item = this.getLogFormatter().formatError(item);
      }
      if (typeof item === 'object' && value !== null) {
        if (references.has(item)) {
          return;
        }
        references.add(item);
      }

      return item;
    };
  }
```

After
```typescript
private removeCircularDependencies(): (key: string, value: LogAttributes | Error | bigint) => void {
    const references = new WeakSet();

    return (key, value) => {
      let item = value;
      if (typeof item === 'bigint') {
        return item.toString();
      }
      if (item instanceof Error) {
        item = this.getLogFormatter().formatError(item);
      }
      if (typeof item === 'object' && value !== null) {
        if (references.has(item)) {
          return;
        }
        references.add(item);
      }

      return item;
    };
  }
```

### Environment

* **Powertools version used**: 1.2.1
* **Packaging format (Layers, npm)**: npm
* **AWS Lambda function runtime:** nodejs16.x
* **Debugging logs:** none

**Comment by dreamorosi** [comment]
Hi @Samuel-Sulo, thank you for reporting this issue.

Please allow us some time to review it and get back to you.

@saragerion, would appreciate your POV on this one before deciding if/how to prioritize it.

**Comment by dreamorosi** [comment]
For future implementer, unless there's a better option, we have settled on implementing this as converting the number to a string (`BigInt.toString()`).

If anyone wants to pick this up, please leave a comment here to discuss the changes before opening a PR.

**Comment by shdq** [comment]
Hey @dreamorosi

I made a quick fix for this and wrote a couple of tests, and I also suggest renaming `removeCircularDependencies()` to `handleTypeErrors()` or even more generic `jsonReplacerFn()` and updating the description since it does more than just remove circular dependencies. I think we covered both of the possible [typeErrors](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#exceptions). Can I open a PR?

I also want to do a small refactor of `removeEmptyKeys()` function. We can get rid of the `pickBy` dependency by rewriting it. It seems like the case when `LogItem` has empty, undefined, and null values is not tested at all. Should I open a new issue about that?

**Comment by dreamorosi** [comment]
Hi @shdq thanks for looking into this one!

This is great to hear, please feel free to open a PR with both changes, since they seem to be relatively connected.

Just like other instances, I'm more than in favor of reducing/removing dependencies as long as the functionality remains the same, which in this case means the output is the same.

Happy to hear also about the extra test cases.

Looking forward to review the PR with both changes, no need to do more "paperwork" on this one.

But thanks a lot for being considerate and asking!
