### ISSUE TITLE
Feature request: `captureMethod` decorator for sync/async methods

### ISSUE THREAD

**Issue by kennethwkz-mm** [aws-powertools/powertools-lambda-typescript#1204]
### Use case

> [!important]
> EDIT: see [this comment](https://github.com/aws-powertools/powertools-lambda-typescript/issues/1204#issuecomment-1736144813) for updated scope & context

For captureMethod - Method decorator able to support both async/sync function together

### Solution/User Experience

We can add new option parameter - async to let user determine when the function need capture sync function.

```
class Something {
  tracer.captureMethod({ async: false })
  public myMethod {
     // do stuff
  }
}
```

### Alternative solutions

```Markdown
const tracer = new Tracer();

const myFunction = () => { //do something  };

const handler = () => {
  const result = tracer.provider.captureFunc('my subsegment name', myFunction);
}
```

### Acknowledgment

- [X] This feature request meets [Lambda Powertools Tenets](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/#tenets)
- [X] Should this be considered in other Lambda Powertools languages? i.e. [Python](https://github.com/awslabs/aws-lambda-powertools-python/), [Java](https://github.com/awslabs/aws-lambda-powertools-java/)

**Comment by dreamorosi** [comment]
Thank you for the feature request.

As discussed on Discord, I think the feature has merit. At the moment the decorator always assumes that the decorated method is `async` and as such it always returns a `Promise` and uses `AWSXRay.captureAsyncFunc` under the hood.

For most cases this is reasonable and/or harmless as it can be awaited by the caller, however I acknowledge that there are other cases in which this is not desirable.

One option to fix this would be the introduction of a parameter where the user specifies whether the decorated function is `async` or not (like the example in your post).

Another option, that should be investigated, would be to see if there's any way in which the decorator is able to automatically determine whether the method its decorating is `sync` or `async`, and based on that adjust its behavior and return type.

**Comment by arnabrahman** [comment]
I can take a look @dreamorosi

**Comment by dreamorosi** [comment]
Hi @arnabrahman, thank you for offering to help on this.

Let's discuss the signature of the new decorator and high level implementation in this issue before opening a PR.

I'd like to understand the extent of the changes before deciding whether we should move forward with it.

If you have any questions please let me know 🙂

**Comment by arnabrahman** [comment]
Sorry for being late. I did some digging, but couldn't find a way for a decorator to determine if the decorated function is sync/async. 

There is a util function in `node.js` (https://nodejs.org/api/util.html#utiltypesisasyncfunctionvalue) which can determine if the function is async but it doesn't work for typescript because typescript transipiles async/await code into a regular function that returns a promise. So, in this case, the util function always returns `false`

```
const util = require('node:util'); 

class Foo {
    async asyncMethod() {}
}

const foo = new Foo();
console.log(util.types.isAsyncFunction(foo.asyncMethod)); // false
```

So, the only way that i can think of this is:

```
function decorator(target: any, propertyKey: string, descriptor: PropertyDescriptor) {
    const originalMethod = descriptor.value;
  
    descriptor.value = function (...args) {
        let result = originalMethod.apply(this, ...args);
        if (result instanceof Promise) {
           console.log('Async method');
        } else {
            console.log('Sync method');
        }
        return result;
    }
}

```
Inside `if` block `captureAsyncFunc` can be applied & inside `else` block `captureFunc` can be applied. But not sure if this is an elegant way to handle this. We can always introduce a new parameter. 

Let me know what you think @dreamorosi

**Comment by dreamorosi** [comment]
Hi @arnabrahman, I've thought about this (sorry for the delay) and I'm not sure it's compatible with the current implementation of the decorator.

Ideally we'd need to know whether `originalMethod` is async or sync before opening the `captureFunc` or `captureAsyncFunc`. Those two functions handle the subsegment for the operation, so we need to call them before calling `originalMethod.apply` (which should be called within the scope of that `capture*`.

We could probably refactor both `captureFunc` & `captureAsyncFunc` out of the implementation and handle the subsegment manually, but I'd rather leave this as last option.

Recently I realised that the `@types/node` package has a type guard called `isAsyncFunc` ([here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/ff9bb7773f62441b845863c0997af9ee5c7d094c/types/node/v14/util.d.ts#L133)), do you think this (or its implementation) could be useful for our purpose here?

**Comment by paddymccarroll** [comment]
Hi - is this behaviour documented anywhere? If not, should it be added to the docs here? https://docs.powertools.aws.dev/lambda/typescript/main/core/tracer/#methods

**Comment by dreamorosi** [comment]
Hi @paddymccarroll - sorry for the late reply.

You are right and this is not explicitly documented in the docs, and our [API docs](https://docs.powertools.aws.dev/lambda/typescript/main/api/classes/_aws_lambda_powertools_tracer.index.Tracer.html#captureMethod) actually seem to suggest you can decorate synchronous methods.

We can definitely improve the docs & call out the limitation. Just out of curiosity: did you hit this limitation wanting to decorate a sync method?

**Comment by paddymccarroll** [comment]
Hi @dreamorosi - no worries, thanks for your reply.

Yep, I had a lot of the methods in my app decorated and only noticed this limitation when the changes were deployed and the app's functionality was broken due to those methods not being awaited. We have the tracing disabled locally, so it's not something I would have noticed there.

**Comment by arnabrahman** [comment]
@dreamorosi Sorry, somehow I missed the notification. And about your suggestion, I am not sure. I think someone else who has a better understanding of javascript can take a look at this issue. Sorry couldn't be of much help here.

**Comment by dreamorosi** [comment]
The previous iteration of the discussion around the issue focused on trying to find a way to use the same decorator to handle both synchronous and asynchronous methods.

With that effort not being successful, we should instead consider handling these two cases a separate and provide two decorators: `captureMethod` and `captureMethodSync` which can be used respectively on async and synchronous methods.

Ideally the bulk of the implementation for these decorators should be abstracted in a shared function and the each decorator should handle only the different signatures and `await`-ing of the decorated method.

Likewise, while working on this we should revisit the types, and specifically the `MethodDecorator` type which at the moment uses `any`. There might not be a better way of expressing this method, however if this is the case we should document this and remove the `TODO` comment in the code:
```ts
// eslint-disable-next-line  @typescript-eslint/no-explicit-any
type MethodDecorator = (target: any, propertyKey: string | symbol, descriptor: TypedPropertyDescriptor<any>) => any;
```

**Comment by shdq** [comment]
> With that effort not being successful, we should instead consider handling these two cases separately and provide two decorators: `captureMethod` and `captureMethodSync` which can be used respectively on async and synchronous methods.

I read the conversation and looked at the decorator code. What if we use `originalMethod.constructor.name === 'AsyncFunction'` to check the original method and conditionally use `captureFunc` or `captureAsyncFunc` to make the decorator handle both sync and async functions? It looks like a quick fix, or am I missing something?

**Comment by dreamorosi** [comment]
> I read the conversation and looked at the decorator code. What if we use originalMethod.constructor.name === 'AsyncFunction' to check the original method and conditionally use captureFunc or captureAsyncFunc to make the decorator handle both sync and async functions? It looks like a quick fix, or am I missing something?

That was my original plan, however I wasn't able to find a way to make it work due to one branch of the function being sync and the other being async. For example, take this function:

```ts
const myFunc = async (method: Callable): X => {
  if (method.constructor.name === 'AsyncFunction') {
    return await traceAsync()
  } else {
     return trace();
  }
}
```

Regardless of the branch evaluated at runtime, it will always be treated as asynchronous and return a promise because we are using the `async` keyword. Conversely, if we don't use the `async` keyword and instead write it synchronously like this:

```ts
const myFunc = (method: Callable): X => {
  if (method.constructor.name === 'AsyncFunction') {
    return traceAsync(); // this is still a pending promise that the caller has to await or .then()
  } else {
     return trace();
  }
}
```

Additionally, when it comes to typing this function, I didn't find any reliable way of making it apply the correct return type. TypeScript expects any function defined as `async` to return a `Promise<T>`, this means that regardless of what we write in it, the return type must be (and is) a promise.

In the past months, when working on the Batch Processing utility, which supports both sync & async record handlers, we ended up with discarding this idea (also because of what [explained here](https://stackoverflow.com/questions/76659881/return-type-of-sync-async-method-based-on-class-property)) and instead be explicit about the type of operation. In that case we created a `BatchProcessor` (async) and a `BatchProcessorSync`.

We adopted `async` as default because most of modern code written in JavaScript is asynchronous, especially in Lambda & when interacting with AWS APIs. This way, even if this means some duplication on our side, customers immediately know what to expect and the types/implementation is also more straightforward.

**Comment by dreamorosi** [comment]
After discussing this internally once again we have decided to not move forward with this feature for the time being, and instead improve our documentation to clarify that our decorators are currently compatible with asynchronous class methods only (#1778).

Before leaving this comment I have also discussed this with @shdq - who was looking into this topic - on Discord and we are aligned on the decision.
