### ISSUE TITLE
Docs: extract Logger code snippets in separate files

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#1220]
### What were you searching in the docs?

Currently the code snippets in the documentation under the Logger's section are hardcoded as part of the page's markdown.

This authoring experience, which doesn't provide linting, is error prone, which causes issues in the docs and in turns to users.

This issue is part of a larger effort being tracked at #729.

### Is this related to an existing documentation section?

https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/logger/

### How can we improve?

The code snippets should be extracted to their own separate files, placed under `docs/snippets/logger`.

So for instance, the first snippet that currently reads:

```ts
import { Logger } from '@aws-lambda-powertools/logger';

const logger = new Logger({ serviceName: 'serverlessAirline' });

export const handler = async (_event, _context): Promise<void> => {
    // ...
};
```

would be replaced with:
```ts
--8<-- "docs/snippets/logger/basicUsage.ts"
```

And the content should be placed in its own file at the path: `docs/snippets/logger/basicUsage.ts`.

This applies to all TypeScript code snippets of the page.

### Acknowledgment

- [X] I understand the final update might be different from my proposed suggestion, or refused.

**Comment by niko-achilles** [comment]
@dreamorosi  Give me the names of the code snippets for Logger so that i can start doing. 

Code Snippets identified: 
1. [section Usage - handler.ts](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#usage)
2. [section Example using AWS Serverless Application Model (SAM) - handler.ts](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#example-using-aws-serverless-application-model-sam)
3. [section Capturing Lambda context info - Middy Middleware](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#capturing-lambda-context-info)
4. [section Capturing Lambda context info - Decorator](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#capturing-lambda-context-info)
5. [section Capturing Lambda context info - Manual](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#capturing-lambda-context-info)
6. [section Loging incoming event - Middy Middleware](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#log-incoming-event)
7.  [section Loging incoming event - Decorator](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#log-incoming-event)
8. [section Appending persistent additional log keys and values - handler.ts](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#appending-persistent-additional-log-keys-and-values)
9. [section Clearing all state - Middy Middleware](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#clearing-all-state)
10. [section Clearing all state - Decorator](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#clearing-all-state)
11. [section Appending additional data to a single log item - handler.ts](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#appending-additional-data-to-a-single-log-item)
12. [section Logging errors - handler.ts](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#logging-errors)
13. [section Using multiple Logger instances across your code - handler.ts](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#using-multiple-logger-instances-across-your-code)
14. [section Sampling logs - handler.ts](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#sampling-logs)
15. [section Custom Log formatter (Bring Your Own Formatter) - handler.ts](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#custom-log-formatter-bring-your-own-formatter)
16. [section Custom Log formatter (Bring Your Own Formatter) - utils/formatters/MyCompanyLogFormatter.ts](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#custom-log-formatter-bring-your-own-formatter)
17. [section Testing your code - handler.test.ts](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/docs/core/logger.md#testing-your-code)

**Comment by dreamorosi** [comment]
Here:

1. `basicUsage.ts`
2. `sam.ts`
3. `middy.ts`
4. `decorator.ts`
5. `manual.ts`
6. `eventMiddy.ts`
7. `eventDecorator.ts`
8. `appendKeys.ts`
9. `clearStateMiddy.ts`
10. `clearStateDecorator.ts`
11. `extraData.ts`
12. `logError.ts`
13. `createChild.ts`
14. `logSampling.ts`
15. `bringYourOwnFormatterHandler.ts`
16. `bringYourOwnFormatterClass.ts`
17. `unitTesting.ts`

**Comment by niko-achilles** [comment]
> How can we improve?
The code snippets should be extracted to their own separate files, placed under docs/snippets/tracer.

Please correct the path `docs/snippets/tracer` under How can we improve ?  in https://github.com/awslabs/aws-lambda-powertools-typescript/issues/1220#issue-1527740259. It should be as I assume `docs/snippets/logger`

So for acceptance we have the 17 named code snippets : https://github.com/awslabs/aws-lambda-powertools-typescript/issues/1220#issuecomment-1380193727

and the location `docs/snippets/logger` of the Logger code snippets . 

Is that ok @dreamorosi ?

**Comment by dreamorosi** [comment]
Yes, that's okay. 

Corrected.
