### ISSUE TITLE
RFC: utilities packages structure

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#125]
## Description of the feature request

We need to come to an agreement on how to structure the utilities packages like `parameters`, `parsers`, etc. for this project.

**Problem statement**

The Python version of Powertools groups all the modules/classes under an `utilities` umbrella module. This is in line with how package management is done in Python and with the way the AWS SDK (`boto3`) is distributed.

The Typescript version seem to be going in the [monorepo](https://en.wikipedia.org/wiki/Monorepo) direction with each utility having [its own published package](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/packages/logger/package.json) and its own dependencies. This choice makes sense also in the context of the newer AWS SDK v3 for Javascript that also has a [modular architecture](https://aws.amazon.com/blogs/developer/modular-packages-in-aws-sdk-for-javascript/).

**Describe alternatives you've considered**

On one hand, favouring consistency with the Python utility all the utilities (`parsers`, `parameters`, etc.) should be under the same utility package. On the other hand splitting each utility in its own package would bring the following benefits:
* Being in line with the other Typescript/Javascript AWS-related projects like AWS SDK v3 and CDK
* Allowing Customers to have closer control over the deployment package size by importing only the dependencies that they need. I.e. If a Customer needs the `parsers` utility but not the `parameters` one there would be no reason to bring dependencies like `@aws-sdk/client-secrets-manager`, `@aws-sdk/client-ssm`, `@aws-sdk/client-dynamodb`, etc. which are not needed for the `parsers` util.

**Comment by TastefulElk** [comment]
Definitely agree with going the modular approach of separate packages. Whilst there's definitely value in keeping reasonably in line with the python implementation, splitting it up into modules will be more flexible for users and tree shaking won't be a soft requirement as the project grows

**Comment by heitorlessa** [comment]
For Python Powertools v2, we're exploring modularization as the entire feature set is 1.4M -- however AWS SDK brings 67M alone.

Whether we modularise or not in v2, we'll remove the "utilities" namespace to make it easier to adapt in other runtimes like TS, and .NET in the future -- note that Java does this already cc @pankajagrawal16

**Comment by m-radzikowski** [comment]
I too think that modularisation and separate packages is the way to go.

However, I would suggest also creating a meta-package containing all the modules as dependencies. Think about it similarly to lodash - you can install `lodash` and have everything or install `lodash.clonedeep`, `lodash.merge`, etc. and have only the parts you need.

Why create this meta-package? For simplicity of usage if you use tree-shaking when bundling your code. If done correctly, you can add the meta-package to dependencies and then have only the required parts bundled with code, so it does not affect the final Lambda size.

The size of the downloaded package doesn't really matter (either 100 KB or 2 MB), it matters what is bundled and uploaded. CDK devs had to have a similar thought since CDK v2 is a single package - you only use it locally, so it does not harm to download libs for all possible Constructs.

**Comment by saragerion** [comment]
@m-radzikowski would you be so kind to create a separated issue for your proposal? I will close this one as it's been implemented.
