### ISSUE TITLE
Maintenance: npm script `package` is incorrect

### ISSUE THREAD

**Issue by Muthuveerappanv** [aws-powertools/powertools-lambda-typescript#1343]
### Expected Behaviour

the main [package.json](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/package.json#L21) has a script `package`. 

Excepted behavior is that it will package the entire workspace. 

### Current Behaviour

Currently it goes in a recursive loop

```
> aws-lambda-powertools-typescript@0.0.1 package
> npm run package


> aws-lambda-powertools-typescript@0.0.1 package
> npm run package


> aws-lambda-powertools-typescript@0.0.1 package
> npm run package


> aws-lambda-powertools-typescript@0.0.1 package
> npm run package


> aws-lambda-powertools-typescript@0.0.1 package
> npm run package
```

### Code snippet

`npm run package`

### Steps to Reproduce

on the root directory of `aws-lambda-powertools-typescript`

run 
```
npm install
npm run package
```

### AWS Lambda Powertools for TypeScript version

latest

### AWS Lambda function runtime

18.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi Muthu, thank you for opening this issue.

You are right, in its current form the command is broken and causes a recursion. I think the issue went unnoticed because we don't really use the command as [we use `lerna`](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/workflows/make-release.yml#L50-L51) to package (for now) and all other commands that are run across the workspace in our CI are always ran with the proper flag to make more explicit what is being run.

Nevertheless, I think for the time being we should fix this.

----

Note: I see that you have already opened a PR, thank you for the bias for action. Next time however, please consider waiting until one of the maintainers has triaged the issue before moving onto a PR.
We try to follow the process described in the contributing guidelines ([here](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/CONTRIBUTING.md#summary)) to make sure that issues have been discussed and their scope has been agreed upon to minimize the risk of investing time on a PR that might not be valid or not get the attention it deserves (in terms of reviews) on a timely manner. Appreciate your understanding!

**Comment by Muthuveerappanv** [comment]
> Hi Muthu, thank you for opening this issue.
> 
> You are right, in its current form the command is broken and causes a recursion. I think the issue went unnoticed because we don't really use the command as [we use `lerna`](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/workflows/make-release.yml#L50-L51) to package (for now) and all other commands that are run across the workspace in our CI are always ran with the proper flag to make more explicit what is being run.
> 
> I am also changing the categorization of the issue from bug to maintenance as the issue doesn't affect runtime behavior (read [_is this a bug?_](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/MAINTAINERS.md#is-that-a-bug)).
> 
> Nevertheless, I think for the time being we should fix this.
> 
> Note: I see that you have already opened a PR, thank you for the bias for action. Next time however, please consider waiting until one of the maintainers has triaged the issue before moving onto a PR. We try to follow the process described in the contributing guidelines ([here](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/CONTRIBUTING.md#summary)) to make sure that issues have been discussed and their scope has been agreed upon to minimize the risk of investing time on a PR that might not be valid or not get the attention it deserves (in terms of reviews) on a timely manner. Appreciate your understanding!

Thank you @dreamorosi, and appreciate the explanation of the PR & Issue process, point noted 👍
Will follow the same in the Issues & PRs to come!
