### ISSUE TITLE
Feature request: Support Middy 4.x

### ISSUE THREAD

**Issue by mk0sojo** [aws-powertools/powertools-lambda-typescript#1694]
### Use case

Middy 4 has been out quite long and if using lambda with Node 18, we want to use Middy 4 because of the AWS SDK v3 support.
Is there any plans to support Middy 4?

Sorry if this is a duplicate, but couldn't find any similar feature request.

### Solution/User Experience

Upgrade middy package

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda-typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
Hi @mk0sojo thanks for opening the issue.

The current latest version of Powertools for AWS supports all currently available Node.js AWS Lambda runtimes: `nodejs14x`, `nodejs16x`, and `nodejs18x`.

With version 4.x Middy dropped support of Node.js 14, which prevents us from recommending it to all our customers since we can't reliably run integration tests on that runtime.

We are aware that Node.js 14 has reached EOL but for the time being we have aligned our runtimes (aka Node.js versions) support with Lambda. This means that we'll drop support for this version in the coming weeks as announced in #1664. 

Shortly after that we'll likely also start recommending Middy 4.x. 

In any case, we only really rely on `@middy/core`, which at the best of my knowledge hasn't introduced any breaking change between versions `3.x` and `4.x`, so if using Node.js 16 or newer you should be able to use it with Powertools.

**Comment by mk0sojo** [comment]
While @middy/core doesn't rely on the AWS SDK, a lot of other middy middlewares does and since v.4 they use AWS SDK v3 rather than AWS SDK v2, for example, the SSM middleware (https://middy.js.org/docs/upgrade/3-4/#ssm). So as part of our upgrade from Node 16 to Node 18 (and AWS SDK v2 to v3). We will therefor hold off using the lambda powertools until Middy 4 is supported.

**Comment by dreamorosi** [comment]
This is available in preview starting from the `2.0.0-alpha.1` release. You can install this version using the `next` tag, i.e. `npm i @aws-lambda-powertools/logger@next`.
