### ISSUE TITLE
Maintenance: Improve security posture by addressing OpenSSF results

### ISSUE THREAD

**Issue by sthulb** [aws-powertools/powertools-lambda-typescript#1799]
### Summary

We recently added OpenSSF Scorecard to the repository, on the initial scan, it found a few actionable items.

### Why is this needed?

OpenSSF Scorecard scanner found minor issues with the project that we should improve on.

### Which area does this relate to?

Governance

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
The "on new PR" workflow is failing due to it attempting to obtain more elevated permissions than the caller workflow - see [an example here](https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/7263820844/workflow).

Would appreciate if you could take a look. 

cc @am29d.

**Comment by dreamorosi** [comment]
The "On PR merge" workflow is also failing due to permission issues: https://github.com/aws-powertools/powertools-lambda-typescript/actions/runs/7292228413/job/19872848955

**Comment by dreamorosi** [comment]
The issues to the PR automations have been fixed in #1978.

@am29d I'm wondering if you'd be okay with us removing the `Create Artifact` step ([here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/b487b878e78267ba2fab93a40df069c7474ac62d/.github/workflows/reusable_publish_docs.yml#L99)) from the docs workflows.

The step requires `actions: write` which apparently lowers our scorecard score, and since it's used in three different workflows (the one that uses it plus two caller ones) it penalizes us 3 times.

With this in mind I would like us to consider removing it from the workflow and troubleshoot in other ways when needed.

What do you think?

**Comment by dreamorosi** [comment]
With the release workflow merged we have completed most of the work needed for the OpenSSF scorecard.

After discussing internally, these are the pending items for the next iteration, after which we can close the topic:
- Add top-level `contents: read` permission to [this workflow](https://github.com/aws-powertools/powertools-lambda-typescript/blob/719e1b9ee4024c6935af1302e281cc42277353f4/.github/workflows/make-version.yml#L4-L5)
- Compare remaining findings from the scorecard with the Python repo, and mark as resolved all the ones that must have `contents: write` by design
- Display scorecard badge on the readme [![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/aws-powertools/powertools-lambda-typescript/badge)](https://api.securityscorecards.dev/projects/github.com/aws-powertools/powertools-lambda-typescript)

**Comment by dreamorosi** [comment]
With #2072 being merged we can now consider concluded the work needed to improve the security posture of the project.

Our current baseline score is 9.3: [![OpenSSF Scorecard](https://api.securityscorecards.dev/projects/github.com/aws-powertools/powertools-lambda-typescript/badge)](https://api.securityscorecards.dev/projects/github.com/aws-powertools/powertools-lambda-typescript)
