### ISSUE TITLE
Docs: remove `logEvent` parameter from Logger constructor setting

### ISSUE THREAD

**Issue by bestickley** [aws-powertools/powertools-lambda-typescript#1814]
### Expected Behaviour

The [docs](https://docs.powertools.aws.dev/lambda/typescript/latest/core/logger/#utility-settings) state that `Logger`'s constructor accepts a `logEvent` parameter to control whether or not logger prints event. But when I try to do this I get an error. See screenshot.
![image](https://github.com/aws-powertools/powertools-lambda-typescript/assets/35735118/de84f0de-2379-4fdb-a3ce-1eefcafc315a)

### Current Behaviour

Cannot pass `logEvent` into constructor of `Logger`.

### Code snippet

```ts
const logger = new Logger({
  logEvent: true, // ERROR: Object literal may only specify known properties, and 'logEvent' does not exist in 'ConstructorOptions'
});
```

### Steps to Reproduce

1. Reproduce code in code snippet above.
2. See error.

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

18.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi @bestickley, thank you for opening the issue.

The documentation is wrong and we'll use this issue to fix it.

The `logEvent` property should not be part of the constructor because even with enabled, it can only work when the Logger is used in conjunction with the `injectLambdaContext` Middy middleware or class method decorator.

This is because we can only log the event when the handler is wrapped by the decorator or middleware. If we allowed the setting in the constructor, this could make customers think that by simply enabling the option Logger will log the event, which is not the case.

We do have an environment variable, but that's mostly to disable the behavior without changing the code either in a dev environment or after deployment.

With this in mind I'm inclined to consider not a bug, not a feature request, but rather an action point to change the docs.

**Comment by kaihendry** [comment]
I don't quite understand what the process is to log the incoming event. 

Idea is to surface it easily, ideally in the AWS console for debugging.

Could that please be documented too?

**Comment by am29d** [comment]
I agree @kaihendry , we can add a small section specifically for logging events.

**Comment by dreamorosi** [comment]
Hi @kaihendry - we do have a section dedicated to this feature - which can be [found here](https://docs.powertools.aws.dev/lambda/typescript/latest/core/logger/#log-incoming-event).

When enabled, the feature instructs the logger instance to emit one log at `INFO` level containing the payload of the `event` for that invocation. Given that this is a regular log, you'll be able to see it in the CloudWatch dashboard in all the same places where you already access logs (Log Groups, Tail, Insights, etc.).

Given that the Logger utility must have access to the function `event` for it to log it, the feature is available only when using the `injectLambdaContext` Middy middleware or `@ injectLambdaContext` class method decorator. This is also why - despite the inaccurate documentation - the setting is not available at the constructor level.

**Comment by am29d** [comment]
> we do have a section dedicated to this feature - which can be [found here](https://docs.powertools.aws.dev/lambda/typescript/latest/core/logger/#log-incoming-event). 

I scanned the outline multiple times and missed it 😵‍💫
