### ISSUE TITLE
Maintenance: Update deprecated dependencies

### ISSUE THREAD

**Issue by Cupprum** [aws-powertools/powertools-lambda-typescript#1915]
### Summary

When i execute the following command:
```
npm run setup-local
```
I can see the following output:
```
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated @aws-sdk/util-base64-node@3.209.0: The package @aws-sdk/util-base64-node has been renamed to @aws-sdk/util-base64. Please install the renamed package.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
```

### Why is this needed?

In order to keep the codebase up to date these dependencies should be updated. This does not look nice when i as a user see that official package from AWS is showing warnings.

### Which area does this relate to?

Other

### Solution

I am happy to work on this issue and propose a PR.

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by dreamorosi** [comment]
Hi @Cupprum thank you for taking the time to open this issue.

After taking a look at the dependencies that you have listed, and that are mentioned in the warnings emitted **when configuring the local development environment** it appears that two out of three of these dependencies are transitive dependencies (aka brought in by some of our dependencies) and that are used only in the development environment.

As you can see from our `package-lock.json` file, both `@npmcli/move-file` and `querystring` are not direct dependencies:
 - `@npmcli/move-file` is brought into the development environment of the project via `lerna > @npmcli/run-script> node-gyp > make-fetch-happen > cacache`
 - `querystring` is brought into the development environment of the project via `aws-sdk`

Given that these are transitive dependencies of which we don't have direct control, I would recommend you to open an issue under the repositories of the project that list them directly as dependency - in this case `lerna` and `aws-sdk` respectively - to ask them to move to the newer versions.

The third dependency `@aws-sdk/util-base64-node` is used directly by the Idempotency and Parameters utility and has been left there intentionally. While the package has been marked as deprecated by the AWS SDK for JavaScript team, this is only due to a name change (`@aws-sdk/util-base64`).

The reason why we haven't moved our utilities to the new module is because some of the AWS Lambda managed runtimes for Node.js still bundle the older package (the one called `@aws-sdk/util-base64-node`) instead of the new one. Using the new one would require all customers using these two Powertools utilities to make sure that the new version (`@aws-sdk/util-base64`) is bundled or otherwise present in the Lambda execution environment. 

We have noticed this a few months ago and looked at both the old and new package and the implementation has remained the same, so in an effort to offer a low friction adoption and usage for our customers we have opted to remain to the older one for the time being.

As already mentioned, the `@npmcli/move-file` and `querystring` **are not used** in the Powertools utilities that are published on npm and that eventually end up in your Lambda functions. The other dependency (`@aws-sdk/util-base64-node`) has been intentionally left as-is as explained above and we will continue to periodically check the Lambda managed runtime and update to `@aws-sdk/util-base64` when it's safe to do so.

With the above in mind I'll be closing this issue and thank you again for opening the issue and for giving us the chance to document these warnings in this thread.

**Comment by Cupprum** [comment]
Thank you and i very much appreciate the transparency.
