### ISSUE TITLE
Feature request: Expose existing IdempotencyRecord in IdempotencyValidationError

### ISSUE THREAD

**Issue by kevin-secrist** [aws-powertools/powertools-lambda-typescript#2048]
### Use case

In my current work I'm reusing the Idempotency package to consolidate potentially many events into one final entity. The first event needs to create the entity, and following events should be updates to that existing entity. The function that has been made idempotent returns the ID of the entity that was created. When the package throws a `IdempotencyValidationError` that is enough for me to trigger an update but it would also be nice to know the entity ID.

For example

```ts
try {
  const createdEntityId = await createThingIdempotent(createRequest)
  return createdEntityId
} catch (error) {
  if (error instanceof IdempotencyValidationError) {
    await handleTheUpdateCase() // example
    // we don't have the entityId here to return
    return -1
  }
  throw error
}
```

I have means of looking up what the entityId is by searching/listing resources, so this is not a blocker for me but having the existing record available seems like a reasonable thing to expect in this kind of workflow. If the payload failing validation is an exceptional scenario, ideally you'd want to be able to recover from it rather than fail outright. In order to recover, I expect you may want to know what data is in conflict.

### Solution/User Experience

Simply exposing the `IdempotencyRecord` or at least the `responseData` in a similar fashion to how it is done with `IdempotencyItemAlreadyExistsError` should be enough to accomplish this.

https://github.com/aws-powertools/powertools-lambda-typescript/blob/f9b7e6c26284174a2b7696c3ad0f9f47c1fe3624/packages/idempotency/src/errors.ts#L6-L13
https://github.com/aws-powertools/powertools-lambda-typescript/blob/f9b7e6c26284174a2b7696c3ad0f9f47c1fe3624/packages/idempotency/src/persistence/BasePersistenceLayer.ts#L156-L161

At the place where this error is currently thrown, the existing record is in scope and should be easy to include.

https://github.com/aws-powertools/powertools-lambda-typescript/blob/f9b7e6c26284174a2b7696c3ad0f9f47c1fe3624/packages/idempotency/src/persistence/BasePersistenceLayer.ts#L317-L326

### Acknowledgment

- [X] This feature request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [X] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by am29d** [comment]
Hey @kevin-secrist ,

thank for raising the issue. We could return the record in the error, since we have it in the scope anyway, similar to `IdempotencyItemAlreadyExistsError`. I am not sure how you can recover from arbitrary validation errors during runtime, unless you have a very narrow use case, where you know exactly what could go wrong and how to recover. 

We see many requests that lead to extending the idempotency with a hook, something where customer can attach their own logic in case of idempotency errors, i.e. collect metrics, redact and log specific information, or recover from validation errors. I can see that your use cases would also fit great into this area. 

For now, I see no issues to return `IdempotencyRecord` inside the `IdempotencyValidationError`.
