### ISSUE TITLE
Docs: error when mocking AppConfigProvider get method

### ISSUE THREAD

**Issue by akhansari** [aws-powertools/powertools-lambda-typescript#2159]
### Expected Behaviour

No TS2353 error

### Current Behaviour

Error TS2353: Object literal may only specify known properties

### Code snippet

Snippet taken from the documentation.
The error occurs at `mockResolvedValueOnce`.

```typescript
import { handler } from './testingYourCodeFunctionsHandler';
import { AppConfigProvider } from '@aws-lambda-powertools/parameters/appconfig';

describe('Function tests', () => {
  const providerSpy = jest.spyOn(AppConfigProvider.prototype, 'get');

  beforeEach(() => {
    jest.clearAllMocks();
  });

  test('it retrieves the config once and uses the correct name', async () => {
    // Prepare
    const expectedConfig = {
      feature: {
        enabled: true,
        name: 'paywall',
      },
    };
    providerSpy.mockResolvedValueOnce(expectedConfig);

    // Act
    const result = await handler({}, {});

    // Assess
    expect(result).toStrictEqual({ value: expectedConfig });
    expect(providerSpy).toHaveBeenCalledTimes(1);
    expect(providerSpy).toHaveBeenCalledWith('my-config');
  });
});
```

### Steps to Reproduce

Run tests with Jest.

### Possible Solution

Adding `// @ts-ignore` before `mockResolvedValueOnce`

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi, thanks for opening this issue.

Right around the time that you opened it we merged a big PR for our new v2 release. Among the changes there were also edits to the code snippet that resembles your use case.

You can see the updated version [here](https://docs.powertools.aws.dev/lambda/typescript/latest/utilities/parameters/#__tabbed_9_1), please let me know if it solves your issue.

**Comment by aviv-akhansari** [comment]
@dreamorosi Great news for the version 2.

About the issue, this will resolve the problem if there is no transform.
But in the case of `provider.get(name, { transform: "json" })`, as the [return value](https://github.com/aws-powertools/powertools-lambda-typescript/blob/d18ffde73f28f1347e39ebe3169d439017539301/packages/parameters/src/types/AppConfigProvider.ts#L111-L124) is not Uint8Array, the issue is still here.

**Comment by dreamorosi** [comment]
Thanks for reporting back.

I'll take a look and get back to you

**Comment by dreamorosi** [comment]
Hi, apologies for the delay.

I have tried to reproduce the issue and wasn't able to, I am testing using the code snippet in the repo [found here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/30b4877ca1d80cbfa016d4016b0512be684d16b7/docs/snippets/parameters/testingYourCodeProvidersHandler.ts#L12) and edited to use the transform.

![image](https://github.com/aws-powertools/powertools-lambda-typescript/assets/7353869/08341304-62b3-49c9-8d68-3775e9f49333)

If you're still seeing the error I think it'd help if you could provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the issue, this way I can clone it on my machine and check the issue.

**Comment by dreamorosi** [comment]
Hi, thank you for sharing an example, I now see what you meant.

To better contextualize the behavior you're seeing it's important to understand how the various Parameters providers work. Each one of them extends the [`BaseProvider` class](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/packages/parameters/src/base/BaseProvider.ts#L39) and provides an implementation for the abstract `_get` method.

In the case of the `AppConfigProvider`, the `_get` method is where the logic needed to communicate with the AppConfig APIs is implemented. This method is called by the extended provider and its result is later transformed as needed.

When calling the `get` method in your code, the logic of the `BaseProvider.get` method is executed first. This involves checking the in-memory cache and if the value is not in cache, then the `_get` method from the provider mentioned above is called. 

The return value of the `_get` method is then used back in the `BaseProvider.get` method and transformed if you selected `json` or `binary`.

With the above in mind, the mock as it's setup in the example is not working but that's expected, since the method you're mocking expects an `Uint8Array` as return value by default - this is because the transforms are applied after that.

There are a couple alternatives that I have tested on your codebase and that work.

The first option would be to use the `getAppConfig` helper function instead of the `AppConfigProvider` in your `lambda.ts`:

```ts
const progressiveRollout = await getAppConfig("ProgressiveRollout", {
  environment: "default",
  application: "my-app",
  transform: "json",
});
```

With this function, you can set the mock in a similar to what you did for the `getParameter`, which means you don't have to worry about transforms and can specify the return value as-is:

```ts
import {
    getAppConfig,
} from "@aws-lambda-powertools/parameters/appconfig"
import { getParameter } from "@aws-lambda-powertools/parameters/ssm"
import { JSONValue } from "@aws-lambda-powertools/commons/types"
import { handler } from "./lambda"

jest.mock("@aws-lambda-powertools/parameters/ssm", () => ({
    getParameter: jest.fn(),
}))
const mockedGetParameter = getParameter as jest.MockedFunction<
    typeof getParameter
>

jest.mock("@aws-lambda-powertools/parameters/appconfig", () => ({
    getAppConfig: jest.fn(),
}))
const mockedAppConfigProvider = getAppConfig as jest.MockedFunction<
    typeof getAppConfig<JSONValue> // <-- Note that we specify the return type here
>

describe("Lambda tests", () => {
    const env = process.env

    beforeEach(() => {
        mockedGetParameter.mockClear()
        mockedAppConfigProvider.mockClear()
        jest.resetModules()
        process.env = { ...env }
    })

    afterEach(() => {
        process.env = env
    })

    test("it returns the correct response", async () => {
        mockedGetParameter.mockResolvedValue("MyName")
        process.env.APP_TEAM = "MyTeam"
        process.env.APP_DOMAIN = "MyDomain"
        // This works now
        mockedAppConfigProvider.mockResolvedValueOnce({ foo: "bar" })

        const result = await handler()

        expect(JSON.parse(result.body)).toEqual({
            message: "Hello MyName",
            team: "MyTeam",
            domain: "MyDomain",
            progressiveRollout: {
                foo: "bar",
            },
        })
    })
})
```

A second option would be to use the `aws-sdk-client-mock` package, which allows you to mock the values returned by the client. This method gives you more control over the behavior of the requests but requires an additional dependency as well as knowledge on the internal implementation of the `AppConfigProvider`:

```ts
import { getParameter } from "@aws-lambda-powertools/parameters/ssm"
import { handler } from "./lambda"
import { Uint8ArrayBlobAdapter } from "@smithy/util-stream"
import { mockClient } from "aws-sdk-client-mock"
import {
    AppConfigDataClient,
    StartConfigurationSessionCommand,
    GetLatestConfigurationCommand,
} from "@aws-sdk/client-appconfigdata"

jest.mock("@aws-lambda-powertools/parameters/ssm", () => ({
    getParameter: jest.fn(),
}))
const mockedGetParameter = getParameter as jest.MockedFunction<
    typeof getParameter
>

describe("Lambda tests", () => {
    const env = process.env
    const client = mockClient(AppConfigDataClient)

    beforeEach(() => {
        mockedGetParameter.mockClear()
        jest.clearAllMocks()
        jest.resetModules()
        process.env = { ...env }
    })

    afterEach(() => {
        client.reset()
        process.env = env
    })

    test("it returns the correct response", async () => {
        mockedGetParameter.mockResolvedValue("MyName")
        process.env.APP_TEAM = "MyTeam"
        process.env.APP_DOMAIN = "MyDomain"

        client
            .on(StartConfigurationSessionCommand)
            .resolvesOnce({
                InitialConfigurationToken: "token",
            })
            .on(GetLatestConfigurationCommand)
            .resolvesOnce({
                Configuration: Uint8ArrayBlobAdapter.fromString(
                    JSON.stringify({ foo: "bar" })
                ),
            })

        const result = await handler()

        expect(JSON.parse(result.body)).toEqual({
            message: "Hello MyName",
            team: "MyTeam",
            domain: "MyDomain",
            progressiveRollout: {
                foo: "bar",
            },
        })
    })
})
```

This second option is what is [mentioned in the docs here](https://docs.powertools.aws.dev/lambda/typescript/latest/utilities/parameters/#__tabbed_9_1).

Overall I acknowledge that there might be some room for improvement in our docs. Additionally, I also think there might be a way to apply a similar pattern to the first option above and pass the generic type to the `AppConfigProvider` mock that would allow you to mock like in your example, but I wasn't able to find it as my `jest` knowledge is somewhat limited in this area.

I hope the above clarifies your question.

**Comment by akhansari** [comment]
This is cristal clear 👍🏻 Thanks for your time and the explanation.
