### ISSUE TITLE
Maintenance: align timestamp formats for `expiration` and `in_progress_expiration` in idempotency table

### ISSUE THREAD

**Issue by RaphaelManke** [aws-powertools/powertools-lambda-typescript#2298]
### Expected Behaviour

I'd expect that the values `expiration` and `in_progress_expiration` are using the same timestamp format

### Current Behaviour
`expiration` uses float numbers
`in_progress_expiration` uses integer 

```json 
{
 "id": "idempotency-powertools#jpdq6YAEvK9dodm3xTODpA==",
 "data": {
  "customerId": "111",
  "notificationId": "1072d969-8277-4d7c-b95b-abd716add0eb",
  "orderId": "ABC"
 },
 "expiration": 1711981471.834,
 "in_progress_expiration": 1711978111637,
 "status": "COMPLETED"
}
```

### Code snippet

See docs examples.

### Steps to Reproduce

* Add Idempotency 
* Look at the dynamodb table 

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

npm

**Comment by dreamorosi** [comment]
Hi @RaphaelManke thanks for opening this issue.

I need to triage this to know for sure, but I would assume that the two formats are different because one (`expiration`) is calculated by Powertools, while the other comes from the Lambda context (`context.getRemainingTimeInMillis()`).

Both timestamps are used in DynamoDB write conditions and compared against a unix timestamps generate using `Date.now()`, so the added precision of one of them should not cause issues.

I think we should probably make the two format consistent, however I'm trying to determine whether this is a bug or just a consistency issue.

Besides consistency and the inaccurate docs, have you encountered any bug related to this?

**Comment by RaphaelManke** [comment]
No I didn't encountered a bug, but there was no other issue type matching 😃

**Comment by dreamorosi** [comment]
It's alright, it wasn't about the issue type - I just wanted to make sure this wasn't causing runtime bugs.

I'm going to label this as `help-wanted`, if anyone is interested in picking it up please leave a comment to let us know. We'll be happy to help you with any question or just review and merge your PR once it's ready.

As part of this task we should update the logic of [this function](https://github.com/aws-powertools/powertools-lambda-typescript/blob/0410648fbc68550c53d48852e5d4507e1c7e51a6/packages/idempotency/src/persistence/BasePersistenceLayer.ts#L256-L260) so that the return value is rounded to an integer number.

**Comment by arnabrahman** [comment]
You can assign me @dreamorosi
