### ISSUE TITLE
Bug: Parser's S3 event notifications schemas

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#2410]
### Summary

Based on the finding in aws-powertools/powertools-lambda-python#4156 it appears that when S3 sends a notification for an object deleted and triggers a Lambda function, the `etag` field is optional.

In looking at our implementation vs the types in `@types/aws-lambda` it seems that we have [a single `S3EventNotificationEventBridgeDetailSchema` schema](https://github.com/aws-powertools/powertools-lambda-typescript/blob/d767d61e74ad49b8b9bcf9c809a1ebef68fad8f9/packages/parser/src/schemas/s3.ts#L68) while DefinitelyTyped has multiple kinds, one for each notification type. 

I'm not sure if we should add schemas for each event type like DefinitelyTyped does or have a single one, however having multiple might help with addressing the subtle differences in field presence (i.e. `etag` not present in delete notifications) & values (i.e. `deletion-type` equals `Permanently Deleted`).

For now I'm opening this as a feature request, but if we decide to just make `etag` optional and keep the schema as-is, we can convert this as maintenance type.

### Why is this needed?

So that customers can use the schema to parse their events.

### Which area does this relate to?

Parser

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by am29d** [comment]
Hmm that's odd because the `@types/aws-lambda` has a required field `etag` on the [notification event payload](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/da465375b16821e859339a5a2034c098f2a5cf25/types/aws-lambda/trigger/s3-event-notification.d.ts#L53-L90). 

It would help to separate them and also narrow down the some of the field values to constants.  Let me run some test events to see, I am a bit uncertain why the it happens "sometime" as stated in the original issue in PT python.

**Comment by dreamorosi** [comment]
Agree, the sometime is throwing me off as well. 

It would make more sense to me that the field is no longer there because the corresponding object has been removed, but the intermittent aspect is strange.

**Comment by am29d** [comment]
I have decided to set the `eTag` to optional for now. The `@types/aws-lambda` are not correct thus we can't rely on them. In addition, splitting the event types would introduce redundancy between the events for common fields, or additional complexity if we decide to split them based on base and specific fields. It'd be hard to read them. 

I need to think of possible scenarios how we could reproduce real event structures, because there is no other way yet to get them correct.
