### ISSUE TITLE
Feature request: export LogLevel values as object

### ISSUE THREAD

**Issue by adityamatt** [aws-powertools/powertools-lambda-typescript#2780]
### Summary

LogLevel for the lambda is currently a type
```
type LogLevelDebug = 'DEBUG';
type LogLevelInfo = 'INFO';
type LogLevelWarn = 'WARN';
type LogLevelError = 'ERROR';
type LogLevelSilent = 'SILENT';
type LogLevelCritical = 'CRITICAL';

type LogLevel = LogLevelDebug | Lowercase<LogLevelDebug> | LogLevelInfo | Lowercase<LogLevelInfo> | LogLevelWarn | Lowercase<LogLevelWarn> | LogLevelError | Lowercase<LogLevelError> | LogLevelSilent | Lowercase<LogLevelSilent> | LogLevelCritical | Lowercase<LogLevelCritical>;

```

Can we turn this into an enum and export it ?

### Why is this needed?

We can import this enum and use it

### Which area does this relate to?

Logger

### Solution

```
enum LogLevel {
    DEBUG = "DEBUG",
    INFO = "INFO",
    ERROR = "ERROR",
    SILENT = "SILENT",
    CRITICAL= "CRITICAL"
}


type LogLevelType = LogLevel | Lowercase<LogLevel>
```

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by am29d** [comment]
Hey @adityamatt , thanks for raising the issue. What is the problem you are trying to solve? Can you share a bit more of context and info why it has to be enum and why it does not work with the current implementation?

**Comment by adityamatt** [comment]
Hi @am29d ,
There is no blocking problem, for now , we need to define a common variable in our codebase and use it as default log level, We add the type check by importing the types from the library. but it could be improved if we could import the enum itself rather than the type and then create the value ourself, it seems too verbose.

Our current use:

```
const DEFAULT_LOG_LEVEL: LogLevel = 'ERROR'


const logger = new Logger({
  logLevel : DEFAULT_LOG_LEVEL
});
```
I propose rather than importing a type and defining a variable, if we can import the enum itself, it would simplify things

```
const logger = new Logger({
  logLevel :  LogLevel.ERROR
});
```

**Comment by dreamorosi** [comment]
Thank you for providing the additional info, I think adding the log levels in a similar way to the one you describe is valid.

As a project, we have been trying to move away from enums and instead use objects with the `as const` notation ([see here as for why](https://www.youtube.com/watch?v=jjMbPt_H3RQ)).

For this specific feature, I would like to see the following:
- [ ] Add a `LogLevel` object in `packages/logger/src/constants.ts` like this:

```ts
const LogLevel = {
  DEBUG: 'DEBUG',
  INFO: 'INFO',
  WARN: 'WARN',
  ERROR: 'ERROR',
  SILENT: 'SILENT',
  CRITICAL: 'CRITICAL',
} as const;
```

- [ ] Import that constant in `packages/logger/src/types/Log.ts` and replace the existing types with this:

```diff
+ import { LogLevel } from '../constants.js';

- type LogLevelDebug = 'DEBUG';
- type LogLevelInfo = 'INFO';
- type LogLevelWarn = 'WARN';
- type LogLevelError = 'ERROR';
- type LogLevelSilent = 'SILENT';
- type LogLevelCritical = 'CRITICAL';

type LogLevel =
-   | LogLevelDebug
-   | Lowercase<LogLevelDebug>
-   | LogLevelInfo
-   | Lowercase<LogLevelInfo>
-   | LogLevelWarn
-   | Lowercase<LogLevelWarn>
-   | LogLevelError
-   | Lowercase<LogLevelError>
-   | LogLevelSilent
-   | Lowercase<LogLevelSilent>
-   | LogLevelCritical
-   | Lowercase<LogLevelCritical>;
+   | (typeof LogLevel)[keyof typeof LogLevel]
+   | Lowercase<(typeof LogLevel)[keyof typeof LogLevel]>;
```

- [ ] Export the newly added `LogLevel` constant in the `packages/logger/src/index.ts` file
- [ ] Modify [this test case here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/3cedd9fdbda5d6bf53d0fa986dcbe8f72271d43a/packages/logger/tests/unit/Logger.test.ts#L600-L602) to use the new `LogLevel.DEBUG` value (this will require importing it [here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/3cedd9fdbda5d6bf53d0fa986dcbe8f72271d43a/packages/logger/tests/unit/Logger.test.ts#L8) and modifying import { LogLevelThresholds, LogLevel } from '../../src/types/Log.js'; to something like `LogLevel as LogLevelType` so that they don't clash.

---

I'm adding the `help-wanted` and `good-first-issue` labels to the issue, if anyone is interested in contributing with a PR, please leave a comment here so I can assign the issue to you.

**Comment by marlapativ** [comment]
@dreamorosi, Can I work on this issue?

Also, from the code I've gone through in the tests, the log levels are set via string as of now. Something like this:
```javascript
const logger = new Logger({
  logLevel: 'ERROR',
});
```

Would it make sense to update all of them to use newly defined `LogLevel` constant ? 
I mean something like this:
```javascript
const logger = new Logger({
  logLevel: LogLevel.ERROR,
});
```
Or should I leave it be?

**Comment by dreamorosi** [comment]
Hi @marlapativ, absolutely you can!

Regarding the tests, I'd like to leave some of them with string so that we can cover that case as well.

Not all users will adopt this new method, but I don't see any issue in converting some to use it.

I'll assign the issue to you, thank you for picking it up!

**Comment by marlapativ** [comment]
@dreamorosi,

I've raised a PR with the changes. I've also randomly updated some tests to use the new constant.

https://github.com/aws-powertools/powertools-lambda-typescript/pull/2787

Please merge if it looks good.

Thanks.
