### ISSUE TITLE
Bug: GetParameterError: Signature expired

### ISSUE THREAD

**Issue by patotech** [aws-powertools/powertools-lambda-typescript#2869]
### Expected Behavior

Currently, we have a provisioned lambda that gets called at least once every 30 seconds, but we expect it to receive at least 2 TPS in a few months. This lambda is configured as an API Authorizer and recovers some parameters from Parameter Store using an "await getSecret". The normal behavior is that the parameter is returned with no issues, but occasionally, we get an exception.

### Current Behavior

At this moment, the lambda is called at least 2800 times a day, but like 4-6 times a day we get this error when calling the `await getSecret` function:

`GetParameterError: Signature expired: <DATE1> is now earlier than <DATE2> (<BASEDATE> - 5 min.)`

Where DATE1 is effectevelly earlier than DATE2 (And DATE2 seems to be BASEDATE - 5min)

At the same time, the log entry in cloudwatch has a timestamp more in-line with BASEDATE. The exception is thrown in the line "const config : string | undefined = await getSecret( securityScopeArn" of the code below.

### Code snippet

```
   private async loadScopeConfig( logger: ILogger) {
        if( this.envContextConfig.isEnvLocal() ) {
            let rawData = fs.readFileSync( process.cwd() + '/local-config/jwt-scopes.json', 'utf8');
            this.securityScopes = JSON.parse( rawData ) as SecurityScopeConfig;
        } else {
            let securityScopeArn : string = process.env[ SecurityManagerConfig.SECURITY_SCOPES_ARN ] as string;
            const config : string | undefined = await getSecret( securityScopeArn, {
                maxAge: 60 * 60
            });
            if( config === undefined ) {
                throw new Error("Could not get configuration from AWS Secrets Manager");
            }
            this.securityScopes = JSON.parse( config ) as SecurityScopeConfig;
        }
    }
```

### Steps to Reproduce

1. I still cannot identify a pattern
2. Seems to require a provisioned lambda
3. It could be related to a time desynchronization if the lambda is "sleep"?

### Possible Solution

I haven't found solutions yet, since the problem arises randomly. I will add some more logs to check the lambda context timestamp and see if there is any way to manage the error gracefully. Currently the exception is thrown in the handler and the lambda fails with `Runtime.UnhandledPromiseRejection`

### Powertools for AWS Lambda (TypeScript) version

latest

### AWS Lambda function runtime

20.x

### Packaging format used

Lambda Layers

### Execution logs

```Shell
2024-07-31T14:14:30.988Z	f934cd98-4292-4a53-a78a-30ad1e0c0dd6	ERROR	Unhandled Promise Rejection 	{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "GetParameterError: Signature expired: 20240731T135915Z is now earlier than 20240731T140930Z (20240731T141430Z - 5 min.)",
    "reason": {
        "errorType": "GetParameterError",
        "errorMessage": "Signature expired: 20240731T135915Z is now earlier than 20240731T140930Z (20240731T141430Z - 5 min.)",
        "name": "GetParameterError",
        "stack": [
            "GetParameterError: Signature expired: 20240731T135915Z is now earlier than 20240731T140930Z (20240731T141430Z - 5 min.)",
            "    at SecretsProvider.get (file:///opt/nodejs/node_modules/@aws-lambda-powertools/parameters/lib/esm/base/BaseProvider.js:92:19)",
            "    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
            "    at async SecurityManagerConfig.loadScopeConfig (file:///opt/nodejs/node_modules/@xyz-module/security/module/classes/SecurityManagerConfig.js:57:28)",
            "    at async SecurityManagerConfig.init (file:///opt/nodejs/node_modules/@xyz-module/security/module/classes/SecurityManagerConfig.js:40:9)",
            "    at async SecurityManager.init (file:///opt/nodejs/node_modules/@xyz-module/security/module/classes/SecurityManager.js:28:9)",
            "    at async XyzLambdaContext.start (file:///opt/nodejs/node_modules/@xyz-module/serverless-lambda/module/classes/XyzLambdaContext.js:21:9)",
            "    at async loadRunnerModule (file:///opt/nodejs/node_modules/@xyz-module/serverless-lambda/module/functions/loadRunnerModule.js:9:5)"
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: GetParameterError: Signature expired: 20240731T135915Z is now earlier than 20240731T140930Z (20240731T141430Z - 5 min.)",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1276:17)",
        "    at process.emit (node:events:519:28)",
        "    at emit (node:internal/process/promises:150:20)",
        "    at processPromiseRejections (node:internal/process/promises:284:27)",
        "    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)"
    ]
}
```
```

**Comment by dreamorosi** [comment]
Hi @patotech, thanks for opening this issue.

The Parser utility uses the AWS SDK v3 for JavaScript to sign and make requests, and the error you're seeing seems to point towards the fact that there might be a delay between when the request is signed (using SigV4) and when it's actually used.

Grossly approximating, when a request is signed with SigV4 the timestamp of the time of signing is used to create the signature. This signature is designed to be valid for a certain amount of time. The error you're seeing points towards the fact that the signature being used might be stale.

Powertools for AWS does not perform the signing. Instead, this is done automatically by the underlying SDK prior to making the request to any AWS API. As far as I know, and as far as this comment from the AWS SDK team says, the signature is done just in time to avoid this type of issue.

It's not the first time I hear about this happening though, and as you already figured out - it's indeed related to using provisioned concurrency, and according to the SDK team it's related to a known issue referred to as the [NodeJs Async Init Problem](https://barker.tech/aws-lambda-nodejs-async-init-88b5c24af567#fd75).

Without knowing your code, it's impossible to tell for sure, but there's a chance that the execution environment gets paused (in waiting for the next invocation), before the portion of the code loading the secret (which is async) is resolved.

Here are two issues I could find on the SDK repo, which show other customers having the same issue with the AWS SDK:
- aws/aws-sdk-js-v3#4429 (closed with no real answer)
- aws/aws-sdk-js-v3#5192 (closed with [a recommendation](https://github.com/aws/aws-sdk-js-v3/issues/5192#issuecomment-2073243617))

Based on the resolution of the thread, the suggestion from the AWS SDK team is to use Top Level Await in your application. This amounts essentially to moving the secret loading outside of your Lambda function handler, so that it's evaluated and completed during the [Init phase](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtime-environment.html#runtimes-lifecycle-ib) and before the environment is "frozen".

The snippet in the issue I linked, translated to use Parser looks like this:

```ts
// ...
const secret = await getSecret(params); // <-- This TLA will not get blocked in Lambda Init stage.

const handler = async (event) => {
  // Use the secret.
}
```

In your case, based on the short code you shared above it seems that you might be using OOP with classes, so you will probably need to do some refactoring to accommodate this.

Note that using TLA requires you to be [using ES Modules](https://aws.amazon.com/blogs/compute/using-node-js-es-modules-and-top-level-await-in-aws-lambda/), which Powertools for AWS supports, but not all other modules out there do. So please take some time to evaluate if this is an option for you.

If this is not an option, or you would like to investigate the issue further, I would suggest opening [a bug report on the aws-sdk-js-v3](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2Cneeds-triage&projects=&template=bug-report.yml&title=TITLE+FOR+BUG+REPORT) repository and have them look into it further and/or provide additional guidance. I'm suggesting this because as I mentioned, the operation causing the issue is at a much lower level in the stack than the one we operate, and thus we don't have control over it.

**Comment by patotech** [comment]
Hi @dreamorosi,

Thanks for the info and for the suggestion, I didn't know of that feature. I will report a bug on the aws-sdj-js-v3 and see where that goes.

Have a nice day 👍
