### ISSUE TITLE
Maintenance: local documentation raises exception when run in docker

### ISSUE THREAD

**Issue by dreamorosi** [aws-powertools/powertools-lambda-typescript#3073]
### Summary

When running the documentation locally using Docker the `mkdocs serve` command seems to fail

Running `docker run --rm -it -p 8000:8000 -v ${PWD}:/docs powertools-typescript/docs`, causes this exception:

```sh
Traceback (most recent call last):
  File "/usr/local/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/__main__.py", line 268, in serve_command
    serve.serve(**kwargs)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 54, in serve
    config = get_config()
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 43, in get_config
    config = load_config(
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/config/base.py", line 374, in load_config
    errors, warnings = cfg.validate()
                       ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/config/base.py", line 231, in validate
    run_failed, run_warnings = self._validate()
                               ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/config/base.py", line 188, in _validate
    self[key] = config_option.validate(value)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/config/base.py", line 55, in validate
    return self.run_validation(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/config/config_options.py", line 868, in run_validation
    return theme.Theme(**theme_config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/theme.py", line 61, in __init__
    self._load_theme_config(name)
  File "/usr/local/lib/python3.11/site-packages/mkdocs/theme.py", line 126, in _load_theme_config
    theme_dir = utils.get_theme_dir(name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mkdocs/utils/__init__.py", line 259, in get_theme_dir
    return os.path.dirname(os.path.abspath(theme.load().__file__))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 399, in abspath
TypeError: expected str, bytes or os.PathLike object, not NoneType
FATA[0000] exit status 1
```

The issue seem to have been introduced in [this PR](https://github.com/aws-powertools/powertools-lambda-typescript/pull/3005/files) and only occurs when using Docker. If I run the docs using Python directly on my machine I am able to run it normally.

Likewise, the build for the docs is also unaffected.

We should investigate why this is happening.

### Why is this needed?

So that contributors in this repo can run the docs locally without having to install Python on their machines.

### Which area does this relate to?

Other

### Acknowledgment

- [X] This request meets [Powertools for AWS Lambda (TypeScript) Tenets](https://docs.powertools.aws.dev/lambda/typescript/latest/#tenets)
- [ ] Should this be considered in other Powertools for AWS Lambda languages? i.e. [Python](https://github.com/aws-powertools/powertools-lambda-python/), [Java](https://github.com/aws-powertools/powertools-lambda-java/), and [.NET](https://github.com/aws-powertools/powertools-lambda-dotnet/)

### Future readers

Please react with 👍 and your use case to help us understand customer demand.

**Comment by am29d** [comment]
Bumping docker image to `2a703999163cdb8257a85849fb2d39914a82587769f95c297bb3f01acf72a609` which is 9.5.35 fixes the issue.

**Comment by leandrodamascena** [comment]
Hey @am29d and @dreamorosi!  dedicated some time tonight to check this issue, and I believe I've identified the root cause. Before going into the details, I must say that I don't understand why we need to use `pip-compile` to generate a `requirements.txt` file with hashes and transitive dependencies in this situation. I mean, I understand that this approach can sometimes be useful to prevent conflicts, but in our current situation it seems to be having the opposite effect: it's actually creating conflicts. 
Maybe in the past it was useful, but right now I don't see any need to use this.

So, can you try to reproduce the fix in your local environment? If it works, I can submit a PR:

1 - Remove the current docker image: `docker image rm powertools-typescript/docs --force`
2 - Clear the contents of the `docs/requirements.txt` file.
3 - Copy the content from `docs/requirements.in` to `docs/requirements.txt`
4 - Remove the flag `--require-hashes` from the `docs/Dockerfile` (line 5)
5 - Build the documentation: `docker build -t powertools-typescript/docs ./docs/`
6 - Run the documentation: `docker run --rm -it -p 8000:8000 -v ${PWD}:/docs powertools-typescript/docs`

![image](https://github.com/user-attachments/assets/a1c18e61-8a77-47c1-b742-8f51a9dfbf3e)

I checked the pipeline for building the documentation and it should not be affected when using `mkdocs build` to build the documentation directly.

While we're at it, why don't you also use the `Makefile` to automate some things? This isn't exclusive to `npm scripts` and you can maintain them, but I think there's a universe of people who might take a while to figure out which npm script to run, whereas the `Makefile` is more straightforward.

Thanks

**Comment by leandrodamascena** [comment]
Hi @dreamorosi, thanks for sharing the OpenSSF scorecard check with me. There is actually a check for `pinned dependencies` if a `pip install` command is found.

The same issue is happening with Python and I figured out the problem. The dependabot is bumping packages and dependencies in the `requirements.txt` file, but it is not smart enough - don't ask me why - to detect that it should bump the transitive dependency `mkdocs` to 1.6.1, which is where the conflict is happening.

If you look [here](https://github.com/aws-powertools/powertools-lambda-typescript/blob/main/docs/requirements.txt#L220), you will see that it is using mkdocs 1.6.0, even though the latest is [1.6.1](https://github.com/mkdocs/mkdocs/releases/tag/1.6.1).

I created a new `requirements.txt` file with the dependencies updated and it's working now. 

This is the first time this has happened and I don't know if it will happen again in the future, but it seems like we don't have many options now.

![image](https://github.com/user-attachments/assets/b9aeef9a-6e66-4aab-a56b-eb4c29d815db)

I'm sending a PR to fix this.
