### ISSUE TITLE
Maintenance: Research & consider alternatives to lerna

### ISSUE THREAD

**Issue by michaelbrewer** [aws-powertools/powertools-lambda-typescript#814]
For quite some time the project was flagged has been unmaintained:

https://github.com/lerna/lerna/issues/2703

But now it is official

![image](https://user-images.githubusercontent.com/5442469/165685459-7c117129-ff9c-4108-ab64-3a50fdafb6db.png)

So we (community + maintainers) should consider an alternative.

**Comment by dreamorosi** [comment]
Hi @michaelbrewer thanks for opening the issue.

We were aware of the status of the tool as this was already mentioned by the creator in some issues, so the announcement is not a surprise.

We have been having discussions about finding alternatives for a while now and this is a topic that we're open to look at after the library reaches General Availability (GA) status.

While this is something that we'll have to address sooner rather than later, at the moment we want to focus on making sure we are nailing the experience for Powertools itself before looking at other corollary topics like this one.

For the sake of other readers that might have less context that you or me, I also want to point out that `lerna` is being used in a fairly limited capacity and mostly to perform actions such as running unit tests and linting, as well as versioning in our CI/CD pipelines.

Nothing related to `lerna` ever ends up in Powertools and on the published artifact on NPM. Additionally, at this stage there's no known vulnerability that affects the tool nor its dependencies.

I'm going to label this issue as an improvement. The unit of work will be prioritized at a later stage and definitely after Powerools for TypeScript reached GA.

We however welcome anyone to provide suggestions for alternatives in this same issue. This will help inform a decision when the time comes.

When doing so please also specify if the suggested tool handles monorepo structure, running of npm scripts in different monorepo packages (ideally in parallel), creation of changelogs, version bump, and npm publishing. We are already using NPM workspaces (`npm 8.x`) to handle dependencies so, some of the features just mentioned might be handled with this same method (i.e. `npm t -ws`).

**Comment by michaelbrewer** [comment]
It's a good time for reviewing options to move to `yarn` and `yarn workspaces`. but there are many floating around now.

Hopefully a clear winner emerges

**Comment by dreamorosi** [comment]
Company behind nx (one of lerna alternatives in the space) has taken over stewardship of lerna:

https://github.com/lerna/lerna/issues/3121

**Comment by dreamorosi** [comment]
Following internal discussion and after looking at the lerna project for the past 2 months we have decided to put this issue on the side for the time being as we have confidence in the near future of the project.

We might reconsider this decision in case the direction of the lerna project changes or its feature set conflicts with our needs.
